version: "3"
services:
  xray:
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    container_name: xray_1.2
    privileged: true
    network_mode: "host"
    environment:
      - PASS=${PASS}
      - UUID=${UUID}
